kind: Pod
apiVersion: v1
metadata:
  name: csi-demo-file
  labels:
    aadpodidbinding: "csi-to-key-vault"
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: keyvault
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: keyvault
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "key-vault-secret-file"