apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLFirewallRule
metadata:
  name: allow-all-mysql
spec:
  resourceGroup: aso-resources
  server: <mysql-server-name>
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255
